// docs/examples/react/src/components/UserProfile.tsx
import { useAuth } from '../hooks/useAuth';

/**
 * Tampilkan info pengguna yang sedang login.
 */
export default function UserProfile() {
  const { user, logout } = useAuth();
  if (!user) return null;

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
      <div
        style={{
          width: 40, height: 40, borderRadius: '50%',
          background: '#005598', color: '#fff',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontWeight: 700, fontSize: '1rem',
        }}
      >
        {user.name.charAt(0).toUpperCase()}
      </div>

      <div>
        <div style={{ fontWeight: 600 }}>{user.name}</div>
        <div style={{ fontSize: '0.85rem', color: '#666' }}>{user.email}</div>
      </div>

      <button
        onClick={logout}
        style={{
          marginLeft: 'auto', padding: '0.4rem 0.9rem',
          border: '1px solid #ccc', borderRadius: 6,
          background: 'none', cursor: 'pointer', fontSize: '0.85rem',
        }}
      >
        Keluar
      </button>
    </div>
  );
}

// docs/examples/svelte/src/components/UserProfile.svelte
<script lang="ts">
  import { user, logout } from '../lib/auth.store';
</script>

{#if $user}
  <div class="user-profile">
    <div class="avatar">{$user.name.charAt(0).toUpperCase()}</div>

    <div class="info">
      <span class="name">{$user.name}</span>
      <span class="email">{$user.email}</span>
    </div>

    <button class="logout-btn" on:click={logout}>Keluar</button>
  </div>
{/if}

<style>
  .user-profile {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }
  .avatar {
    width: 40px; height: 40px;
    border-radius: 50%;
    background: #005598;
    color: #fff;
    display: flex; align-items: center; justify-content: center;
    font-weight: 700;
  }
  .info {
    display: flex;
    flex-direction: column;
  }
  .name  { font-weight: 600; }
  .email { font-size: 0.85rem; color: #666; }
  .logout-btn {
    margin-left: auto;
    padding: 0.4rem 0.9rem;
    border: 1px solid #ccc;
    border-radius: 6px;
    background: none;
    cursor: pointer;
    font-size: 0.85rem;
  }
</style>
